version: "3.8"

services:

   ygg-rss-proxy:
      build: .
      container_name: ygg-rss-proxy
      ports:
         - 8080:8080
      environment:
         TZ: Europe/Paris
         FLARESOLVERR_HOST: byparr
         LOG_LEVEL: DEBUG
      volumes:
         - ./config:/app/config
      env_file:
         - ygg_credentials.env
      restart: unless-stopped
      depends_on:
         - byparr

   byparr:
      image: ghcr.io/thephaseless/byparr:main
      container_name: byparr
      environment:
         TZ: Europe/Paris
         LOG_LEVEL: DEBUG
      ports:
         - 8191:8191
      restart: unless-stopped