services:
   ygg-rss-proxy:
      build: .
      container_name: ygg-rss-proxy
      ports:
         - 8080:8080
      environment:
         TZ: Europe/Paris
         YGG_USER: 'StOpCouDflaE'
         YGG_PASS: 'BaDaSS'
         YGG_URL: "https://www.yggtorrent.top"
         FLARESOLVERR_HOST: flaresolverr
         LOG_LEVEL: INFO
      volumes:
         - ./config:/app/config
      restart: unless-stopped
      depends_on:
         - flaresolverr

   flaresolverr:
      image: 21hsmw/flaresolverr:nodriver
      container_name: flaresolverr
      environment:
         TZ: Europe/Paris
         LOG_LEVEL: info
         CAPTCHA_SOLVER: none
      expose:
         - 8191
      restart: unless-stopped
